layout_spectrum: 0.5386321711360412
typography_spectrum: 0.44933612138032913
color:
  saturation: 0.1911117125764526
  brandStrength: 0.469377338225022
  lightness: 0.3019616874460463
  brandColors:
    - '#334D5C'
    - '#45B29D'
    - '#EFC94C'
    - '#E27A3F'
    - '#DF5A49'
  rhythmicContrast: 0.3335149877807955
coverPrefs:
  filter: false
content_rating:
  adult: false
author:
  name: ''
  url: ''
logo: null
name: ❍▲☰
url: 'http://effortlesssort.money'
navigation:
  - name: Youtube
    url: 'https://www.youtube.com/channel/UCK-BpQQFXaLIsPe5moxDJ3A'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c97c6f33-3420-40f9-a88e-1b773355a573.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c97c6f33-3420-40f9-a88e-1b773355a573.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/667ccdf3-c80f-4975-83a6-9dee5514c7a6.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/667ccdf3-c80f-4975-83a6-9dee5514c7a6.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose: []
github: true
analytics:
  google: UA-93677250-1
