title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c97c6f33-3420-40f9-a88e-1b773355a573.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c97c6f33-3420-40f9-a88e-1b773355a573.jpg
    metadata:
      author: []
      datePublished: null
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
      related: []
      app_links: []
      '@context': 'http://schema.org'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/667ccdf3-c80f-4975-83a6-9dee5514c7a6.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/667ccdf3-c80f-4975-83a6-9dee5514c7a6.jpg
    metadata:
      author: []
      datePublished: null
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
      related: []
      app_links: []
      '@context': 'http://schema.org'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: ''
color:
  saturation: 1
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  rhythmicContrast: 1
coverPrefs:
  filter: false
navigation:
  - name: Youtube
    url: 'https://www.youtube.com/channel/UCK-BpQQFXaLIsPe5moxDJ3A'
    type: external
analytics:
  google: UA-93677250-1
favicon: null
name: ❍▲☰
author:
  name: ''
  url: ''
logo: null
typography_spectrum: 0.1111708
layout_spectrum: 1
content_rating:
  adult: false
url: 'http://effortlesssort.money'
